[package]
name = "feature"
version = "0.1.0"
edition = "2021"
description = "See which features are enabled and WHY"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
