[package]
name = "feature"
version = "0.1.0"
edition = "2021"
description = "See which features are enabled and WHY"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.15.2"
clap = { version = "4.0.9", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
rstest = "0.16.0"

# Optional dependencies
rayon = { version = "1.5.1" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
