[package]
name = "feature"
version = "0.3.1"
edition = "2021"
description = "See how features and dependencies got enabled by your crate."
license = "GPL-3.0-only"
source = "https://github.com/ggwpez/feature"

[dependencies]
cargo_metadata = "0.15.2"
clap = { version = "4.0.9", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"

[dev-dependencies]
rstest = "0.16.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
