[package]
name = "feature"
version = "0.3.2"
edition = "2021"
description = "See out how Rust dependencies and features are enabled."
license = "GPL-3.0-only"
source = "https://github.com/ggwpez/feature"

[[bin]]
name = "feature"
src = "src/main.rs"

[dependencies]
btreemultimap = { version = "0.1.0", default-features = false }
cargo_metadata = "0.15.2"
clap = { version = "4.0.9", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
regex = "1.7.1"
serde_json = "1.0.92"

[dev-dependencies]
rstest = "0.16.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 3
